// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeInclusionScanner
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeInclusionScanner.593d698d-a4d7-4f9a-b764-b86a42bc2621";
        public const string Name = "CodeInclusionScanner";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Satya Prakash Parida";
        public const string Tags = "";
    }
}
