// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeInclusionScanner
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CodeInclusionScannerString = "3dbf3fdb-a044-4ce1-8e41-95379f1b286c";
        public static Guid CodeInclusionScanner = new Guid(CodeInclusionScannerString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CodeInclusionScannerGroup = 0x0001;
        public const int CodeInclusionScannerCommand = 0x0100;
    }
}